spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    druid:
      url: jdbc:mysql://139.224.119.184:3306/oms?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false # 开发时关闭缓存,不然没法看到实时页面
    mode: LEGACYHTML5 # 用非严格的 HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
  aop:
    proxy-target-class: true
  redis:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    sentinel:
      master: mymaster
      nodes: 139.224.117.172:26379, 139.224.117.172:26380, 139.224.117.172:26381
  rabbitmq:
    host: 139.224.117.172
    port: 5672
    username: rabbit
    password: 123456

server:
  port: 8502

# MyBatis Config properties
mybatis:
  type-aliases-package: cn.com.connext.oms.entity
  mapper-locations: classpath:mapper/*.xml
  # 驼峰
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
#logging:
#  level:
#    org.caps.website: trace
#  file: log/springboot.log
#  pattern:
#    file: .%d{yyyy-MM-dd} [%thread]  %-5level  %logger{50}  %msg%n
#    console: .%d{yyyy-MM-dd} === [%thread] === %-5level === %logger{50} ==== %msg%n

